version: '3'

services:

  flux-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - PYTHONPATH="${PYTHONPATH}:/."
    image: flux-test:new
    command: python -m unittest /test/test_closure.py

  flux:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH="${PYTHONPATH}:/."
    image: flux:new

